version: '3.8'

services:
  db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: next-prisma-db
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: